### ISSUE TITLE
Framebuffer Bug : Uncaught AssertionError: undefined == true

### ISSUE THREAD

**Issue by bryaan** [uber/luma.gl#478]
I am trying to create a FrameBuffer, but have a strange error.  Looks like a bug.

const offScreenBuffer = new Framebuffer(gl)

```
assert.js:60 Uncaught AssertionError: undefined == true
    at pushContextState (/Users/bryan/Developer/tibra/tibra-charts/node_modules/luma.gl/dist/webgl-utils/track-context-state.js:407:24)
    at withParameters (/Users/bryan/Developer/tibra/tibra-charts/node_modules/luma.gl/dist/webgl/context-state.js:243:43)
    at Texture2D.setImageData (/Users/bryan/Developer/tibra/tibra-charts/node_modules/luma.gl/dist/webgl/texture.js:429:40)
    at Texture2D.initialize (/Users/bryan/Developer/tibra/tibra-charts/node_modules/luma.gl/dist/webgl/texture.js:298:12)
    at new Texture2D (/Users/bryan/Developer/tibra/tibra-charts/node_modules/luma.gl/dist/webgl/texture-2d.js:58:11)
    at Framebuffer._createDefaultAttachments (/Users/bryan/Developer/tibra/tibra-charts/node_modules/luma.gl/dist/webgl/framebuffer.js:719:52)
    at Framebuffer.initialize (/Users/bryan/Developer/tibra/tibra-charts/node_modules/luma.gl/dist/webgl/framebuffer.js:171:28)
    at new Framebuffer (/Users/bryan/Developer/tibra/tibra-charts/node_modules/luma.gl/dist/webgl/framebuffer.js:129:11)
    at Object.onCheckIntersects (webpack-internal:///148:76:31)
    at eval (webpack-internal:///146:6:26)
```

**Comment by 1chandu** [comment]
@bryaan gl.state  is created when `trackContextState` is called, which should be called by default during context creation , here : https://github.com/uber/luma.gl/blob/1474437a9244483c17e48ec77160bfa977c89045/src/webgl/context.js#L110 , `manageState` is true by default.  Can you put a breakpoint here and check?

What version of luma.gl are you using? Any other errors in console? (set luma.log.priority=2).

**Comment by bryaan** [comment]
@1chandu Ok I will try that stuff out and report back.

I believe this could be related to my problem and solution here https://github.com/uber/luma.gl/issues/477

For some reason Luma.gl cannot create a gl context in electron.  However, if I do what I did there it works just fine.  I already have lots done with Luma.gl in electron so it doesn't seem there should be any major issues, just minor bugs.

For some reason though this doesn't seem to work with the Framebuffer.

**Comment by bryaan** [comment]
Using 'webgl' instead of 'webgl2' produces a different error

```js
      const gl = canvas.getContext('webgl')
      const framebuffer = new Framebuffer(gl, {
        webgl2: true,
        // manageState: false,
        width: 100,
        height: 100,
        throwOnError: true,
        debug: true,
      })
```

```
Uncaught (in promise) AssertionError: Invalid WebGLRenderingContext
    at assertWebGLContext (.../node_modules/luma.gl/dist/webgl/context.js:69:24)
    at Framebuffer.Resource (.../node_modules/luma.gl/dist/webgl/resource.js:42:38)
    at new Framebuffer (.../node_modules/luma.gl/dist/webgl/framebuffer.js:122:112)
    at AnimationLoop.onInitialize [as _onInitialize] (webpack-internal:///145:54:25)
    at .../node_modules/luma.gl/dist/core/animation-loop.js:156:24
    at <anonymous>
```

**Comment by bryaan** [comment]
Ok now we are getting somewhere.  So because the environment is electron the isBrowser check fails.  This has to be updated. https://github.com/uber/luma.gl/blob/1474437a9244483c17e48ec77160bfa977c89045/src/webgl/context.js#L89

If I set the isBrowser param to to true the context creation and Framebuffer creation 'work' but I have this error:
```js
     const gl2 = createGLContext({
        // manageState: false,
        wegl2: true,
        webgl1: true,
        throwOnError: true,
        debug: true,
      })
      const framebuffer = new Framebuffer(gl2, {
        webgl2: true,
        manageState: false,
        width: 1024,
        height: 1024,
        throwOnError: true,
        debug: true,
      })
```

```
Uncaught (in promise) TypeError: Cannot read property 'insertBefore' of undefined
    at /Users/bryan/Developer/tibra/tibra-charts/node_modules/luma.gl/dist/webgl-utils/create-canvas.js:65
    at <anonymous>
```

Uncaught (in promise) TypeError: Cannot read property 'insertBefore' of undefined
    at /Users/bryan/Developer/tibra/tibra-charts/node_modules/luma.gl/dist/webgl-utils/create-canvas.js:65
    at <anonymous>

**Comment by bryaan** [comment]
With the isBrowser=true hack I get a strange failure of Matrix4().ortho() which was working fine when I created the context myself.

```js

const Engine = ({ canvas }) => {
  const animationLoop = new AnimationLoop({
    onInitialize ({ gl, canvas, width, height }) {
      setParameters(gl, {
        clearColor: [0, 0, 0, 1],
        clearDepth: [1],
        depthTest: true,
        depthFunc: gl.LEQUAL
      })
      const glfb = createGLContext({
        // wegl2: false,
        // webgl1: true,
        // throwOnError: true,
        // debug: true,
      })
      const framebuffer = new Framebuffer(glfb, {
        width: 1024,
        height: 1024,
      })
      return { framebuffer, glfb }
    },
    onRender (context) {
      const {
        gl, width, height, aspect, useDevicePixels
      } = context

      const camera = new Matrix4().ortho({
        left: -width / 2,
        right: width / 2,
        top: height / 2,
        bottom: -height / 2,
        near: -100,
        far: 500
      })

      gl.clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT)
    }
  })

  const gl = createGLContext({
    debug: false
  })

  animationLoop.setProps({
    autoResizeViewport: true,
    autoResizeDrawingBuffer: true,
    useDevicePixels: true
  })
  animationLoop.start({ gl })
}
```

```
.../node_modules/math.gl/dist/math-array.js:sourcemap:1 Uncaught Error: Invalid Matrix4
    at Array.check (.../node_modules/math.gl/dist/math-array.js:sourcemap:1)
    at Array.ortho (.../node_modules/math.gl/dist/matrix4.js:sourcemap:1)
    at AnimationLoop.onRender [as _onRender] (Engine.js?34ef:241)
    at AnimationLoop._renderFrame (.../node_modules/luma.gl/dist/core/animation-loop.js:sourcemap:243)
```

**Comment by ibgreen** [comment]
```js
      const gl = canvas.getContext('webgl')
      const framebuffer = new Framebuffer(gl, {
        webgl2: true,
        // manageState: false,
        width: 100,
        height: 100,
        throwOnError: true,
        debug: true,
      })
```
FWIW - This code doesn't look right. You are providing context creation parameters to the Framebuffer constructor...

**Comment by ibgreen** [comment]
> Uncaught Error: Invalid Matrix4

This is simply math.gl trying to help by validating that your matrix entries contain numbers and non `NaN` or other "junk". 

Most likely inputs, i.e. `width` and `height` did not contain valid values.

(Note to self: the math.gl error message could be clearer.)

**Comment by ibgreen** [comment]
math.gl comment improvements: https://github.com/uber-web/math.gl/pull/17

**Comment by bryaan** [comment]
const gl = createGLContext({
    canvas,
  })

I should have added the canvas as so.  Now the path in createGLContext where canvas is created  works because it isn't called.

Now the only issue is isBrowser needs to return true if it's an Electron context.  Are contributions from Uber outsiders welcome?  Should we add an isElectron or add the functionality to isBrowser?

**Comment by ibgreen** [comment]
> Now the only issue is isBrowser needs to return true if it's an Electron context.

@bryaan @jianhuang01  See #482

**Comment by ibgreen** [comment]
Please try luma.gl v5.1.6
