### ISSUE TITLE
polyfillContext initialization throws exception when getSupportedExtensions returns null

### ISSUE THREAD

**Issue by wentsul** [uber/luma.gl#807]
When using deck.gl, we're seeing a lot of client errors related to luma.gl. It's been mostly happening on Windows 10/Chrome 70.

Stack trace:
```
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of object
  at initializeExtensions(../../node_modules/luma.gl/dist/es5/webgl-context/polyfill-context.js:215:1)
  at polyfillContext(../../node_modules/luma.gl/dist/es5/webgl-context/polyfill-context.js:289:1)
  at call(../../node_modules/luma.gl/dist/es5/webgl/resource.js:46:1)
  at (unknown)(../../node_modules/luma.gl/dist/es5/webgl/framebuffer.js:133:1)
  at _getPickingBuffer(../../node_modules/@deck.gl/core/dist/es5/lib/layer-manager.js:645:1)
  at pickObject(../../node_modules/@deck.gl/core/dist/es5/lib/layer-manager.js:431:1)
  at _pickAndCallback(../../node_modules/@deck.gl/core/dist/es5/lib/layer-manager.js:989:1)
  at handler(../../node_modules/@deck.gl/core/dist/es5/lib/layer-manager.js:968:1)
  at i(../../node_modules/@deck.gl/core/node_modules/mjolnir.js/src/event-manager.js:298:11)
  at emit(../../node_modules/hammerjs/hammer.js:2519:1)
  at callback(../../node_modules/@deck.gl/core/node_modules/mjolnir.js/src/event-manager.js:347:18)
  at apply(../../node_modules/@deck.gl/core/node_modules/mjolnir.js/src/inputs/move-input.js:98:16)
  at (unknown)(../../node_modules/raven-js/src/raven.js:376:1)
```

The error happens in the `initializeExtensions` function within `polyfill-context.js`. It looks like that function may return null in some senarios (when context is lost).

Looks like the return type in the webGL specification is `sequence<DOMString>? getSupportedExtensions();`. See https://www.khronos.org/registry/webgl/specs/latest/1.0/

`initializeExtensions` should be updated to handle null.

#### Actual Result

Stack trace listed above.

#### Expected Result

No exception thrown.

#### Reproduce Steps

```
const canvas = document.createElement('canvas');
const gl = canvas.getContext('webgl');
const ext = gl.getExtension('WEBGL_lose_context');
ext.loseContext();
gl.getSupportedExtensions(); // returns null
```

**Comment by 1chandu** [comment]
`?` notation represents a possible `null` value, as per spec there are several other functions can return `null`.

**Comment by ibgreen** [comment]
> ? notation represents a possible null value, as per spec there are several other functions can return null.

Good point. I took a quick look, I think the other cases are expected and as far as I can tell we handle them all. We just missed that `getExtensions` would return `null` instead of an empty array, rather surprising design choice on part of the standard, but easily worked around now that we know.

**Comment by ibgreen** [comment]
@XiaokaiUber @wentsul Should we mark this for 6.3.2 and cherry-pick?

**Comment by XiaokaiUber** [comment]
@wentsul Do you need this in 6.3.2 patch?

**Comment by wentsul** [comment]
@XiaokaiUber I'm on a much older version of `deck.gl` so I'll just upgrade to latest.

**Comment by 1chandu** [comment]
@wentsul luma.gl 6.3.2 published with this fix, you can lock luma dependency to this version in your application. Please re-open if you see any issues.
