### ISSUE TITLE
Required gl version is too old

### ISSUE THREAD

**Issue by stevenbeeckman** [uber/luma.gl#82]
```bash
alubox:luma.gl-master stevenbeeckman$ npm install
npm WARN prefer global node-gyp@3.3.1 should be installed with -g

> gl@2.1.5 install /Users/stevenbeeckman/Downloads/luma.gl-master/node_modules/gl
> prebuild --download

prebuild WARN install Prebuilt binaries for node version 0.10.40,0.12.7,1.0.4,1.8.4,2.4.0,3.3.1,4.1.1 are not available
prebuild ERR! configure error
prebuild ERR! stack Error: Invalid version number: 0.10.40,0.12.7,1.0.4,1.8.4,2.4.0,3.3.1,4.1.1
prebuild ERR! stack     at getNodeDir (/Users/stevenbeeckman/Downloads/luma.gl-master/node_modules/node-gyp/lib/configure.js:69:25)
prebuild ERR! stack     at /Users/stevenbeeckman/Downloads/luma.gl-master/node_modules/node-gyp/lib/configure.js:41:7
prebuild ERR! stack     at /Users/stevenbeeckman/Downloads/luma.gl-master/node_modules/node-gyp/lib/configure.js:393:9
prebuild ERR! stack     at ChildProcess.exithandler (child_process.js:193:7)
prebuild ERR! stack     at emitTwo (events.js:106:13)
prebuild ERR! stack     at ChildProcess.emit (events.js:191:7)
prebuild ERR! stack     at maybeClose (internal/child_process.js:850:16)
prebuild ERR! stack     at Socket.<anonymous> (internal/child_process.js:323:11)
prebuild ERR! stack     at emitOne (events.js:96:13)
prebuild ERR! stack     at Socket.emit (events.js:188:7)
prebuild ERR! not ok
prebuild ERR! build Error: Invalid version number: 0.10.40,0.12.7,1.0.4,1.8.4,2.4.0,3.3.1,4.1.1
prebuild ERR! build     at getNodeDir (/Users/stevenbeeckman/Downloads/luma.gl-master/node_modules/node-gyp/lib/configure.js:69:25)
prebuild ERR! build     at /Users/stevenbeeckman/Downloads/luma.gl-master/node_modules/node-gyp/lib/configure.js:41:7
prebuild ERR! build     at /Users/stevenbeeckman/Downloads/luma.gl-master/node_modules/node-gyp/lib/configure.js:393:9
prebuild ERR! build     at ChildProcess.exithandler (child_process.js:193:7)
prebuild ERR! build     at emitTwo (events.js:106:13)
prebuild ERR! build     at ChildProcess.emit (events.js:191:7)
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! gl@2.1.5 install: `prebuild --download`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the gl@2.1.5 install script 'prebuild --download'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --download
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gl
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls gl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/stevenbeeckman/Downloads/luma.gl-master/npm-debug.log
```

Adapting `package.json` so `"gl": "^3.0.5"` makes `npm install` work.

**Comment by ibgreen** [comment]
@stevenbeeckman Bumped gl to latest v4.0.1 as that version of headless-gl was created to support luma.gl. hopefully that version of gl installs for you, if not please file a bug on gl. 

Also, published on npm as luma.gl@1.0.1.
